### ISSUE TITLE
Doesn't have examples

### ISSUE THREAD

**Issue by cassio-vo** [dotnet/dotnet-api-docs.pt-br#10]
Doesn't have examples

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a4484428-7a0b-e18b-85f9-f91dd552fd35
* Version Independent ID: c4a4a71c-780c-fa16-5a57-8a6826f947c9
* Content: [EndpointDispatcher.ChannelDispatcher Property (System.ServiceModel.Dispatcher)](https://docs.microsoft.com/pt-br/dotnet/api/system.servicemodel.dispatcher.endpointdispatcher.channeldispatcher?view=netframework-4.8)
* Content Source: [xml/System.ServiceModel.Dispatcher/EndpointDispatcher.xml](https://github.com/dotnet/dotnet-api-docs.pt-br/blob/live/xml/System.ServiceModel.Dispatcher/EndpointDispatcher.xml)
* Product: **dotnet-api**
* Technology: **system.servicemodel**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @cassio-vo 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @cassio-vo 

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by cassio-vo** [comment]
An code example, with method and import.
This wioll be great.
    Em segunda-feira, 27 de maio de 2019 15:19:38 BRT, Cecilia Acevedo <notifications@github.com> escreveu:  
 
 
Closed #10.

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2507](https://github.com/dotnet/dotnet-api-docs/issues/2507) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @cassio-vo

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/2507

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
