### ISSUE TITLE
Document better how this method works on different platforms

### ISSUE THREAD

**Issue by andre-ss6** [dotnet/dotnet-api-docs.pt-br#14]
Currently this method documentation for .Net Core is the same as the .Net Framework 4.8, which [obviously] seem to have been written with a Windows-only usage in mind. 

It's not clear what happens on Unix when the three mentioned checks fail and then it's even less clear what happens when it falls under the fourth point. I guess the Windows directory isn't returned under Unix?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a81b4c67-7b0d-56c2-eccc-ef34b4ed2dca
* Version Independent ID: c05a5cc0-6c59-7954-eb46-e162419a5126
* Content: [Path.GetTempPath Method (System.IO)](https://docs.microsoft.com/pt-br/dotnet/api/system.io.path.gettemppath?view=netcore-2.2)
* Content Source: [xml/System.IO/Path.xml](https://github.com/dotnet/dotnet-api-docs.pt-br/blob/live/xml/System.IO/Path.xml)
* Product: **dotnet-api**
* Technology: **system.io**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2620](https://github.com/dotnet/dotnet-api-docs/issues/2620) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @andre-ss6 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/2620

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
